version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ../public:/var/www/html
    links:
            - web:web
    container_name: nginx

  web:
    build: ./phpfpm
    volumes:
      - ../public:/var/www/html
    container_name: web
